"""Tests for the expo_hackatron region built from the official sample CSV.

The region file is generated by tools/build_expo_region.py from
data/sample_hackatron.csv (official MunichTech EXPO sample feed). These tests
pin the structural contract (nodes/links/gateways), the calibration defaults
and that all four strategies run on it.

Run: python3 -m unittest discover -s tests -v
"""

import unittest

from signalflow.network import (
    DEFAULT_VPH, Compiled, list_regions, load_network, run_region,
)


class TestExpoHackatronRegion(unittest.TestCase):
    def setUp(self):
        try:
            self.net = load_network("expo_hackatron")
        except ValueError:
            self.skipTest("expo_hackatron region not built (run "
                          "tools/build_expo_region.py data/sample_hackatron.csv)")

    def test_listed_in_regions(self):
        ids = [r["id"] for r in list_regions()]
        self.assertIn("expo_hackatron", ids)

    def test_structure(self):
        self.assertEqual(len(self.net.nodes), 12)      # 6 intersections + 6 stubs
        self.assertEqual(len(self.net.links), 28)     # 2x(6 ring + 2 chords) + 12 stubs
        signals = [n for n in self.net.nodes if n.get("signal")]
        self.assertEqual(len(signals), 6)
        for n in self.net.nodes:
            self.assertIn("lat", n)
            self.assertIn("lon", n)
            self.assertGreaterEqual(n["deg"], 1)
        for l in self.net.links:
            self.assertGreater(l["length_m"], 0)
            self.assertGreaterEqual(l["lanes"], 1)
            ids = {n["id"] for n in self.net.nodes}
            self.assertIn(l["from"], ids)
            self.assertIn(l["to"], ids)

    def test_compiled_gateways_exist(self):
        c = Compiled(self.net)
        # stubs must give the OD layer entries/exits; all links valid
        self.assertEqual(c.n_links, 28)
        self.assertGreaterEqual(len(c.signalized), 6)

    def test_calibration_defaults(self):
        self.assertEqual(DEFAULT_VPH.get("expo_hackatron"), 2500)
        st = [r for r in list_regions() if r["id"] == "expo_hackatron"][0]["stats"]
        self.assertEqual(st["default_vph"], 2500)
        self.assertEqual(st["default_window"], ["07:00", "09:00"])
        self.assertEqual(st["default_scenario"], "custom")
        self.assertEqual(st["sample_cycle_s"], 90)
        self.assertTrue(st.get("source_short"))
        self.assertTrue(st.get("assumptions"))

    def test_strategies_run_and_adaptive_beats_fixed(self):
        res = run_region("expo_hackatron", {
            "duration_min": 15, "total_vph": 2500, "warmup_min": 0,
            "time_from": "07:00", "time_to": "07:15",
            "demand_scenario": "custom", "demand_profile": "flat",
        })
        s = res["summary"]
        for k in ("fixed", "fixed_tuned", "adaptive", "coordinated"):
            self.assertIn(k, s, f"strategy {k} missing")
            self.assertGreater(s[k]["served"], 0)
        self.assertLess(s["adaptive"]["avg_delay_s"], s["fixed"]["avg_delay_s"])

    def test_deterministic(self):
        cfg = {"duration_min": 10, "total_vph": 2500, "warmup_min": 0}
        a = run_region("expo_hackatron", cfg)["summary"]["adaptive"]
        b = run_region("expo_hackatron", cfg)["summary"]["adaptive"]
        self.assertEqual(a["avg_delay_s"], b["avg_delay_s"])
        self.assertEqual(a["served"], b["served"])


if __name__ == "__main__":
    unittest.main()
